/**
 * DD engine (pi-py) — per-section calls & prompt engineering (extreme depth).
 * Evidence: phoenician-intelligence `src/core/workflow.py` sections_order,
 * `reportGenerator.py` SECTION_* , engine packs under `src/engines/*`,
 * `.cursor/projects/phoenician-intelligence/section-map.md`.
 * Never invent edges.
 */

/**
 * @typedef {{ kind: string, callee: string, purpose: string, auth?: string }} SectionCall
 * @typedef {{
 *   id: string,
 *   name: string,
 *   prompt?: string,
 *   model?: string,
 *   kind?: string,
 *   detail?: string,
 * }} SectionStep
 * @typedef {{
 *   id: string,
 *   name: string,
 *   genOrder: number,
 *   deps: string[],
 *   templates: string[],
 *   writer: string,
 *   models: string[],
 *   calls: SectionCall[],
 *   steps?: SectionStep[],
 *   langfuse?: string[],
 *   flags?: string[],
 *   engine?: string,
 *   notes?: string,
 *   subs?: {
 *     id: string,
 *     name: string,
 *     templates: string[],
 *     models: string[],
 *     calls: SectionCall[],
 *     steps?: SectionStep[],
 *     notes?: string,
 *   }[],
 * }} DdSection
 */

/** Production generation order from workflow.py (not the simpler reportGenerator loop). */
export const ddGenOrder = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "1", "11"];

/** Parallel pairs in production workflow */
export const ddParallelPairs = [
  ["2", "10"],
  ["6", "7"],
];

/** Phases before / around section writing */
export const ddPipelinePhases = [
  {
    id: "data",
    name: "Data collection",
    detail:
      "CapIQ Excel first (exclusive session), then Company Review / PDF crawler in parallel. AlphaSense collect currently hard-skipped in orchestrator.",
    calls: [
      { kind: "data_fetch_market", callee: "CapIQ Playwright → Excel/PDF", purpose: "Financials & filings → EFS" },
      { kind: "data_fetch_web", callee: "Company Review / SerpAPI / ScraperAPI", purpose: "Trustpilot, Reddit, NPS, IR" },
      { kind: "data_write_internal", callee: "EFS /app/companies/{ticker}", purpose: "raw dumps + markers" },
    ],
  },
  {
    id: "index",
    name: "RAG index setup",
    detail:
      "Vertex AI Search primary when USE_VERTEX_AI_SEARCH; Gemini File Search / AlphaSense File Search behind flags (defaults often false).",
    calls: [
      { kind: "embedding_rag", callee: "Vertex Discovery Engine + GCS", purpose: "section RAG corpus" },
      { kind: "embedding_rag", callee: "Gemini File Search", purpose: "PDF corpus" },
      { kind: "embedding_rag", callee: "AlphaSense → Gemini FS", purpose: "AS RAG for §5 & §11" },
    ],
  },
  {
    id: "querygen",
    name: "Agentic query-gen prefetch",
    detail: "If USE_AGENTIC_QUERIES + QUERY_GEN_PARALLEL_ENABLED — AGENTIC_QUERY_MODEL = claude-sonnet-4-6.",
    calls: [
      { kind: "reasoning_llm", callee: "Anthropic claude-sonnet-4-6 (batches)", purpose: "per-section retrieval queries" },
    ],
  },
  {
    id: "rag",
    name: "RAG prefetch",
    detail: "rag_prefetch.py parallel section retrieval; AlphaSense static queries for §5 and §11.",
    calls: [{ kind: "embedding_rag", callee: "Vertex / Gemini / AS", purpose: "RAG_Retrieval_Section_{n}" }],
  },
  {
    id: "web",
    name: "Web research prefetch",
    detail: "sections_needing_web = [2,3,4,5,6,7,8] via Perplexity sonar-pro; templates research/web_search_prompt_section{N}.jinja.",
    calls: [
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Parallel_Web_Search for §2–8" },
    ],
  },
  {
    id: "cio",
    name: "CIO lens (optional)",
    detail: "Investor memory → section question/table injection for §§1–7,9. §8 advisory questions → UE-DCF.",
    calls: [
      { kind: "data_fetch_internal", callee: "EC2 SSH + SQLite memory", purpose: "CIO analog questions" },
      { kind: "reasoning_llm", callee: "Claude (cio_lens prompts)", purpose: "route tables / section asks" },
    ],
  },
  {
    id: "sections",
    name: "Section generation",
    detail: "Order [2,3,4,5,6,7,8,9,10,12,1,11]. §12 RFW background from t≈0; collect before §1. Parallel 2∥10 and 6∥7.",
    calls: [],
  },
  {
    id: "assemble",
    name: "Assemble + callback",
    detail: "Write report to EFS → .NET /internal/callbacks/report-completed. Langfuse REPORT_GENERATION.",
    calls: [
      { kind: "data_write_internal", callee: "EFS reports + progress.json", purpose: "persist DD" },
      { kind: "job_orchestrate", callee: ".NET report-completed", purpose: "job done → SSE", auth: "callback secret" },
    ],
  },
];

/** @type {DdSection[]} */
export const ddSections = [
  {
    id: "2",
    name: "Company Overview",
    genOrder: 1,
    deps: [],
    templates: [
      "templates/sections/section_2.jinja",
      "templates/research/web_search_prompt_section2.jinja",
      "src/retrieval/queries/query2.py",
    ],
    writer: "call_claude_writing_web",
    models: ["claude-sonnet-4-6"],
    engine: "workflow section loop (+ CJA append)",
    langfuse: ["LLM_Call_Section_2", "RAG_Retrieval_Section_2", "Parallel_Web_Search"],
    flags: ["USE_AGENTIC_QUERIES", "USE_VERTEX_AI_SEARCH"],
    notes: "No deps. Parallel with §10. Prefetch web + RAG + CapIQ/EFS financials upstream. CJA (§2.5) appended into overview.",
    calls: [
      { kind: "reasoning_llm", callee: "Anthropic claude-sonnet-4-6 + web_search tool", purpose: "Write §2 overview" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Prefetch web context §2" },
      { kind: "embedding_rag", callee: "Vertex / Gemini File Search", purpose: "RAG for §2 aspects" },
      { kind: "data_fetch_market", callee: "CapIQ Excel on EFS", purpose: "Financial / company tables" },
    ],
    steps: [
      {
        id: "2.prefetch",
        name: "Prefetch (upstream)",
        detail: "Agentic queries → RAG_Retrieval_Section_2 → Parallel_Web_Search (sonar-pro)",
        kind: "embedding_rag",
      },
      {
        id: "2.write",
        name: "Section write",
        prompt: "templates/sections/section_2.jinja",
        model: "claude-sonnet-4-6 via call_claude_writing_web",
        kind: "reasoning_llm",
      },
      {
        id: "2.cja",
        name: "Append Customer Journey (§2.5)",
        detail: "customer_journey_workflow → markdown spliced into §2",
        kind: "reasoning_llm",
      },
    ],
    subs: [
      {
        id: "2.5",
        name: "Customer Journey (CJA)",
        templates: [
          "cja_prompts/cja_step1_context_and_personas.jinja",
          "cja_prompts/cja_step2_discovery_comparison_macro.jinja",
          "cja_prompts/cja_step3_unit_economics.jinja",
          "cja_prompts/cja_step4_friction_analysis.jinja",
          "cja_prompts/cja_step5_value_drivers_and_synthesis.jinja",
          "cja_prompts/cja_step6_section_drafting.jinja",
          "src/retrieval/queries/query2_5.py",
        ],
        models: ["gemini-2.5-pro", "Perplexity", "claude-sonnet-4-6"],
        notes:
          "src/engines/customer_journey_workflow. Steps 1/3–5 Gemini structured; step 2 Perplexity then Gemini parse; step 6 Claude draft ~1200–1500 words.",
        calls: [
          { kind: "reasoning_llm", callee: "Gemini 2.5 Pro structured", purpose: "CJA steps 1,3–5" },
          { kind: "reasoning_llm", callee: "Perplexity (+ Gemini parse)", purpose: "CJA step 2 research" },
          { kind: "reasoning_llm", callee: "claude-sonnet-4-6", purpose: "CJA step 6 draft" },
          { kind: "embedding_rag", callee: "RAG prefetch 2.5", purpose: "customer-journey aspects" },
          { kind: "data_fetch_web", callee: "Company Review / SerpAPI / ScraperAPI", purpose: "Trustpilot/Reddit/NPS inputs" },
        ],
        steps: [
          {
            id: "cja1",
            name: "Step 1 — Context & personas",
            prompt: "cja_step1_context_and_personas.jinja",
            model: "call_gemini_structured → Step1Response",
            kind: "reasoning_llm",
            detail: "1–3 MECE personas + business_model_classification",
          },
          {
            id: "cja2",
            name: "Step 2 — Discovery / comparison / macro",
            prompt: "cja_step2_discovery_comparison_macro.jinja",
            model: "Perplexity (prose) → Gemini structured parse",
            kind: "reasoning_llm",
            detail: "Per persona; Phase A web, Phase B schema",
          },
          {
            id: "cja3",
            name: "Step 3 — Unit economics",
            prompt: "cja_step3_unit_economics.jinja",
            model: "Gemini structured",
            kind: "reasoning_llm",
          },
          {
            id: "cja4",
            name: "Step 4 — Friction analysis",
            prompt: "cja_step4_friction_analysis.jinja",
            model: "Gemini structured",
            kind: "reasoning_llm",
          },
          {
            id: "cja5",
            name: "Step 5 — Value drivers & synthesis",
            prompt: "cja_step5_value_drivers_and_synthesis.jinja",
            model: "Gemini structured",
            kind: "reasoning_llm",
          },
          {
            id: "cja6",
            name: "Step 6 — Section drafting",
            prompt: "cja_step6_section_drafting.jinja",
            model: "claude-sonnet-4-6",
            kind: "reasoning_llm",
            detail: "Full §2.5 markdown",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Team & Culture",
    genOrder: 2,
    deps: ["2"],
    templates: [
      "templates/sections/section_3.jinja",
      "templates/research/web_search_prompt_section3.jinja",
      "src/retrieval/queries/query3.py",
    ],
    writer: "call_claude_writing_web",
    models: ["claude-sonnet-4-6"],
    langfuse: ["LLM_Call_Section_3", "RAG_Retrieval_Section_3"],
    notes: "Needs §2. CapIQ people/ownership tables + web + RAG.",
    calls: [
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 + web_search", purpose: "Write §3" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Prefetch web §3" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §3" },
      { kind: "data_fetch_market", callee: "CapIQ people / ownership tables", purpose: "Team inputs" },
    ],
    steps: [
      { id: "3.prefetch", name: "Prefetch web + RAG", kind: "embedding_rag" },
      {
        id: "3.write",
        name: "Section write",
        prompt: "section_3.jinja",
        model: "call_claude_writing_web",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "4",
    name: "Competitors",
    genOrder: 3,
    deps: ["2"],
    templates: [
      "templates/sections/section_4.jinja",
      "templates/research/web_search_prompt_section4.jinja",
      "src/retrieval/queries/query4.py",
      "templates/utils_prompts/get_competitors.jinja",
      "cw_prompts/get_competitors_step1_profile.jinja",
      "cw_prompts/get_competitors_step2_candidates.jinja",
      "cw_prompts/get_competitors_step3_rank.jinja",
    ],
    writer: "call_claude_writing (no writing_web on final)",
    models: ["gemini-2.5-pro", "claude-opus-4-6", "claude-sonnet-4-6"],
    engine: "competitors_workflow companion + section write",
    langfuse: ["LLM_Call_Section_4"],
    notes: "Feeds competitors_json → §5. H2H is a separate optional job, not this section writer.",
    calls: [
      { kind: "reasoning_llm", callee: "Gemini 2.5 Pro", purpose: "CW step1 company profile" },
      { kind: "reasoning_llm", callee: "Gemini 2.5 Pro + Google Search", purpose: "CW step2 candidates" },
      { kind: "reasoning_llm", callee: "claude-opus-4-6 thinking", purpose: "CW step3 rank/select" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 writing", purpose: "Write §4 body" },
      { kind: "reasoning_llm", callee: "Perplexity (+ revenue_web_search)", purpose: "Prefetch / revenue web" },
      { kind: "data_fetch_market", callee: "CapIQ competitor segments / Excel", purpose: "Comp financials" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §4" },
    ],
    steps: [
      {
        id: "cw1",
        name: "CW Step 1 — Profile",
        prompt: "get_competitors_step1_profile.jinja",
        model: "call_gemini (Gemini 2.5 Pro)",
        kind: "reasoning_llm",
      },
      {
        id: "cw2",
        name: "CW Step 2 — Candidates",
        prompt: "get_competitors_step2_candidates.jinja",
        model: "call_gemini_web (Gemini + Search)",
        kind: "reasoning_llm",
      },
      {
        id: "cw3",
        name: "CW Step 3 — Rank",
        prompt: "get_competitors_step3_rank.jinja",
        model: "call_claude_thinking claude-opus-4-6 (retries 0/30/60s)",
        kind: "reasoning_llm",
      },
      {
        id: "4.write",
        name: "Section 4 body",
        prompt: "section_4.jinja",
        model: "call_claude_writing",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "5",
    name: "Total Addressable Market",
    genOrder: 4,
    deps: ["2", "4"],
    templates: [
      "templates/sections/section_5.jinja",
      "templates/research/web_search_prompt_section5.jinja",
      "src/retrieval/queries/query5.py",
      "src/retrieval/alphasense_queries/query_5.py",
      "tam prompts/industry_and_competitor_tam.jinja",
      "tam prompts/synthesis_prompt.jinja",
      "tam prompts/compression_prompt.jinja",
    ],
    writer: "TAM engine + Claude synthesis",
    models: ["sonar-deep-research", "claude-sonnet-4-6"],
    engine: "tam_commentary_research_workflow / generate_tam_section",
    langfuse: ["LLM_Call_Section_5", "RAG_Retrieval_Section_5"],
    notes: "AlphaSense RAG used here (with §11). Perplexity deep research for TAM industry/competitor.",
    calls: [
      { kind: "reasoning_llm", callee: "Perplexity sonar-deep-research", purpose: "TAM industry/competitor research" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 call_claude", purpose: "Synthesis" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 call_claude_writing", purpose: "Compression" },
      { kind: "embedding_rag", callee: "AlphaSense RAG + Vertex/Gemini", purpose: "§5 retrieval" },
      { kind: "data_fetch_market", callee: "CapIQ", purpose: "Market / financial context" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Prefetch web §5" },
    ],
    steps: [
      {
        id: "tam.research",
        name: "Deep research",
        prompt: "industry_and_competitor_tam.jinja",
        model: "call_perplexity2 sonar-deep-research",
        kind: "reasoning_llm",
      },
      {
        id: "tam.synth",
        name: "Synthesis",
        prompt: "synthesis_prompt.jinja",
        model: "call_claude",
        kind: "reasoning_llm",
      },
      {
        id: "tam.compress",
        name: "Compression",
        prompt: "compression_prompt.jinja",
        model: "call_claude_writing",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "6",
    name: "Market Positioning",
    genOrder: 5,
    deps: ["2", "4", "5"],
    templates: [
      "templates/sections/section_6.jinja",
      "templates/research/web_search_prompt_section6.jinja",
      "src/retrieval/queries/query6.py",
    ],
    writer: "call_claude_writing_web",
    models: ["claude-sonnet-4-6"],
    langfuse: ["LLM_Call_Section_6"],
    notes: "Parallel with §7 (ThreadPoolExecutor pair). Deps 2,4,5.",
    calls: [
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 + web_search", purpose: "Write §6" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Prefetch web §6" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §6" },
    ],
    steps: [
      { id: "6.prefetch", name: "Prefetch web + RAG", kind: "embedding_rag" },
      {
        id: "6.write",
        name: "Section write (∥ §7)",
        prompt: "section_6.jinja",
        model: "call_claude_writing_web",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "7",
    name: "Performance & Estimates",
    genOrder: 6,
    deps: ["2", "5"],
    templates: [
      "templates/sections/section_7.jinja",
      "templates/research/web_search_prompt_section7.jinja",
      "src/retrieval/queries/query7.py",
    ],
    writer: "call_claude_writing_web",
    models: ["claude-sonnet-4-6"],
    langfuse: ["LLM_Call_Section_7"],
    notes: "Deps 2,5 (not 6). Parallel with §6 — SECTION_DEPENDENCIES[7]=[2,5].",
    calls: [
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 + web_search", purpose: "Write §7" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Prefetch web §7" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §7" },
      { kind: "data_fetch_market", callee: "CapIQ financials", purpose: "Estimates / performance tables" },
    ],
    steps: [
      { id: "7.prefetch", name: "Prefetch web + RAG + CapIQ", kind: "data_fetch_market" },
      {
        id: "7.write",
        name: "Section write (∥ §6)",
        prompt: "section_7.jinja",
        model: "call_claude_writing_web",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "8",
    name: "Valuation (DCF)",
    genOrder: 7,
    deps: ["2", "4", "5", "6", "7"],
    templates: [
      "templates/sections/section_8.jinja",
      "templates/sections/dcf_executive_summary_prompt.jinja",
      "ue prompts/unit_economics_discovery_prompt.jinja",
      "ue prompts/rag_dcf_extraction_prompt.jinja",
      "ue prompts/dcf_context_extraction_prompt.jinja",
      "ue prompts/constraints_guidance_prompt.jinja",
      "ue prompts/generate_dcf_model_prompt.jinja",
      "ue prompts/code_sanity_review_prompt.jinja",
      "ue prompts/sanity_gate_correction_prompt.jinja",
      "ue prompts/code_review_prompt.jinja",
      "ue prompts/code_correction_prompt.jinja",
      "ue prompts/bs_balance_gate_prompt.jinja",
      "ue prompts/pv_coherence_gate_prompt.jinja",
      "ue prompts/pv_coherence_gate_high_prompt.jinja",
      "ue prompts/documentation_prompt.jinja",
      "src/services/llm_clients/dcf_llm.py",
      "src/engines/unit_economics_workflow/dcf_llm_registry.py",
    ],
    writer: "UEDCFWorkflow.run + Claude exec summary",
    models: [
      "DCF_LLM_PROVIDER ∈ {openai→gpt-5.5, claude→fable/opus/sonnet, grok→grok-4.3, deepseek→v4-flash}",
      "claude-sonnet-4-6 (post-UE §8 prose if not via call_dcf_writing)",
    ],
    engine: "unit_economics_workflow (UE-DCF + LibreOffice + P/V gate 0.3–3.0)",
    langfuse: ["LLM_Call_Section_8"],
    flags: ["DCF_LLM_PROVIDER", "SKIP_PV_COHERENCE_GATE", "SKIP_STEP3C_BS_BALANCE_GATE"],
    notes:
      "Roles via dcf_llm_registry.DCFStepRole. Default provider often openai/gpt-5.5. LibreOffice recalc = binary_media. Optional Brain DCF playbook inject. §8.5 comps after UE.",
    calls: [
      { kind: "reasoning_llm", callee: "call_dcf_llm (STRUCTURED/EXTRACTION/…)", purpose: "UE-DCF discovery→docs" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 / call_dcf_writing", purpose: "§8 executive summary after UE" },
      { kind: "embedding_rag", callee: "Vertex / Gemini into UE Step 1", purpose: "DCF RAG extract" },
      { kind: "data_fetch_market", callee: "CapIQ Financials Excel + yfinance", purpose: "Price/FX/beta + statements" },
      { kind: "binary_media", callee: "LibreOffice soffice", purpose: "Workbook recalc + P/V gate" },
      { kind: "data_write_internal", callee: "EFS DCF artefacts + pipeline_trace/", purpose: "Model + markers" },
    ],
    steps: [
      {
        id: "ue0",
        name: "Step 0 — UE discovery",
        prompt: "unit_economics_discovery_prompt.jinja",
        model: "DCFStepRole.STRUCTURED → unit_economics_spec JSON",
        kind: "reasoning_llm",
        detail: "Modeling tier + fundamental unit + assumptions",
      },
      {
        id: "ue1",
        name: "Step 1 — RAG extraction (filings)",
        prompt: "rag_dcf_extraction_prompt.jinja",
        model: "DCFStepRole.EXTRACTION",
        kind: "reasoning_llm",
      },
      {
        id: "ue1b",
        name: "Step 1b — Report context extraction",
        prompt: "dcf_context_extraction_prompt.jinja",
        model: "DCFStepRole.EXTRACTION",
        kind: "reasoning_llm",
        detail: "From prior sections; skipped if none",
      },
      {
        id: "ue1c",
        name: "Step 1c — Constraints & guidance map",
        prompt: "constraints_guidance_prompt.jinja",
        model: "DCFStepRole.CONSTRAINTS",
        kind: "reasoning_llm",
        detail: "Binding / strong / reference_only; CIO advisory optional",
      },
      {
        id: "ue2",
        name: "Step 2 — 7-tab openpyxl codegen",
        prompt: "generate_dcf_model_prompt.jinja",
        model: "DCFStepRole.CODEGEN (+ beta/WACC enforce post-process)",
        kind: "reasoning_llm",
      },
      {
        id: "ue2b",
        name: "Step 2b — Financial sanity review",
        prompt: "code_sanity_review_prompt.jinja",
        model: "DCFStepRole.SANITY_REVIEW",
        kind: "reasoning_llm",
        detail: "Optional 2b-fix via sanity_gate_correction_prompt.jinja",
      },
      {
        id: "ue3",
        name: "Step 3 — Code review",
        prompt: "code_review_prompt.jinja",
        model: "role maps to CODE_FIX path / review",
        kind: "reasoning_llm",
        detail: "Step 3b correction if issues (code_correction_prompt.jinja)",
      },
      {
        id: "ue3c",
        name: "Step 3c — BS balance gate",
        prompt: "bs_balance_gate_prompt.jinja",
        model: "DCFStepRole.BS_BALANCE_GATE (claude-opus-4-8 if Claude)",
        kind: "reasoning_llm",
        detail: "Skip if SKIP_STEP3C_BS_BALANCE_GATE=true",
      },
      {
        id: "ue4",
        name: "Step 4 — Compilation verification",
        model: "(no LLM)",
        kind: "job_orchestrate",
        detail: "Syntax/completeness; may loop back to Step 2 once",
      },
      {
        id: "ue5",
        name: "Step 5 — Execute → .xlsx",
        model: "subprocess sandbox",
        kind: "job_orchestrate",
      },
      {
        id: "ue56",
        name: "Step 5.6 — LibreOffice cache values",
        model: "soffice",
        kind: "binary_media",
      },
      {
        id: "ue58",
        name: "Step 5.8 — P/V coherence gate",
        prompt: "pv_coherence_gate(_high)_prompt.jinja",
        model: "DCF LLM + patches; band ~0.3–3.0",
        kind: "reasoning_llm",
        detail: "Skip if SKIP_PV_COHERENCE_GATE",
      },
      {
        id: "ue6",
        name: "Step 6 — Documentation",
        prompt: "documentation_prompt.jinja",
        model: "DCFStepRole.DOCUMENTATION",
        kind: "reasoning_llm",
      },
      {
        id: "ue7",
        name: "§8 executive summary",
        prompt: "dcf_executive_summary_prompt.jinja / section_8.jinja",
        model: "call_claude_writing or call_dcf_writing (WRITING role)",
        kind: "reasoning_llm",
      },
    ],
    subs: [
      {
        id: "8.5",
        name: "Comparables",
        templates: ["templates/sections/section_8_5.jinja", "src/retrieval/queries/query8_5.py"],
        models: ["claude-sonnet-4-6"],
        notes: "Skipped if §4 missing. CapIQ competitor Financials → aggregate_competitor_financials.",
        calls: [
          { kind: "reasoning_llm", callee: "claude-sonnet-4-6 + web_search", purpose: "Write §8.5 comps" },
          { kind: "embedding_rag", callee: "RAG prefetch 8.5", purpose: "Comps retrieval" },
          { kind: "data_fetch_market", callee: "CapIQ competitor Financials Excel", purpose: "Public comps tables" },
        ],
        steps: [
          {
            id: "85.agg",
            name: "Aggregate competitor financials",
            model: "CapIQ Excel → tables",
            kind: "data_fetch_market",
          },
          {
            id: "85.write",
            name: "Write comps section",
            prompt: "section_8_5.jinja",
            model: "call_claude_writing_web",
            kind: "reasoning_llm",
          },
        ],
      },
    ],
  },
  {
    id: "9",
    name: "Financial Health",
    genOrder: 8,
    deps: ["2", "5", "7", "8"],
    templates: [
      "templates/sections/section_9.jinja",
      "src/retrieval/queries/query9.py",
      "cashflow_bridge/prompts/cashflow_bridge_prompt.jinja",
      "cashflow_bridge/prompts/capital_structure_liquidity_tables_prompt.jinja",
      "cashflow_bridge/prompts/template_classification_prompt.jinja",
    ],
    writer: "CF bridge precompute + call_claude_writing_web",
    models: ["claude-opus-4-6", "claude-sonnet-4-6"],
    engine: "cashflow_bridge",
    langfuse: ["LLM_Call_Section_9"],
    notes: "No Perplexity prefetch for §9. Bridge + capital/liquidity use Opus thinking; classification Sonnet; section write Sonnet web.",
    calls: [
      { kind: "reasoning_llm", callee: "claude-opus-4-6 streaming+thinking", purpose: "Cashflow bridge + capital/liquidity tables" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6", purpose: "Template classification cache" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 + web_search", purpose: "Write §9" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §9" },
      { kind: "data_fetch_market", callee: "CapIQ sheets", purpose: "CF / BS inputs" },
    ],
    steps: [
      {
        id: "cf.class",
        name: "Template classification",
        prompt: "template_classification_prompt.jinja",
        model: "claude-sonnet-4-6",
        kind: "reasoning_llm",
      },
      {
        id: "cf.bridge",
        name: "Cashflow bridge",
        prompt: "cashflow_bridge_prompt.jinja",
        model: "call_claude_streaming_with_thinking (opus)",
        kind: "reasoning_llm",
      },
      {
        id: "cf.cap",
        name: "Capital structure / liquidity tables",
        prompt: "capital_structure_liquidity_tables_prompt.jinja",
        model: "call_claude_streaming_with_thinking (opus)",
        kind: "reasoning_llm",
      },
      {
        id: "9.write",
        name: "Section write",
        prompt: "section_9.jinja",
        model: "call_claude_writing_web",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "10",
    name: "Technical Indicators",
    genOrder: 9,
    deps: [],
    templates: [
      "templates/sections/section_10.jinja",
      "tiw_prompts/step1_sentiment_research.jinja",
      "tiw_prompts/step2_unified_technical_section.jinja",
      "tiw_prompts/step1_integrate_context.jinja",
      "tiw_prompts/step2_sentiment_structure.jinja",
      "tiw_prompts/step3_trend_structure.jinja",
      "tiw_prompts/step4_momentum_indicators.jinja",
      "tiw_prompts/step5_chart_patterns.jinja",
      "tiw_prompts/step6_trading_signals.jinja",
      "tiw_prompts/step7_final_section.jinja",
      "tiw_prompts/step8_advanced_structure.jinja",
      "src/retrieval/queries/query10.py",
    ],
    writer: "TIW generate_section10 (owns output)",
    models: ["sonar-deep-research", "claude-sonnet-4-6"],
    engine: "technical_indicators_workflow",
    langfuse: ["LLM_Call_Section_10"],
    notes: "Independent. Parallel with §2. yfinance 5y daily (XLS fallback). Hot path: calc → sentiment → unified Claude write.",
    calls: [
      { kind: "data_fetch_market", callee: "yfinance 5y daily", purpose: "Price series for indicators" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-deep-research", purpose: "TIW sentiment research" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6", purpose: "Unified technical section write" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §10" },
    ],
    steps: [
      {
        id: "tiw1a",
        name: "Step 1A — Chart data",
        model: "Pure Python (no LLM)",
        kind: "data_fetch_market",
        detail: "tiw_calculators",
      },
      {
        id: "tiw1b",
        name: "Step 1B — Advanced indicators",
        model: "Pure Python (no LLM)",
        kind: "job_orchestrate",
      },
      {
        id: "tiw1c",
        name: "Step 1C — Sentiment research",
        prompt: "step1_sentiment_research.jinja",
        model: "Perplexity sonar-deep-research",
        kind: "reasoning_llm",
      },
      {
        id: "tiw2",
        name: "Step 2 — Unified technical section",
        prompt: "step2_unified_technical_section.jinja",
        model: "claude-sonnet-4-6 (single call)",
        kind: "reasoning_llm",
        detail: "Older multi-step templates (step3–8) exist; hot path uses unified write",
      },
    ],
  },
  {
    id: "12",
    name: "Red Flags",
    genOrder: 10,
    deps: [],
    templates: [
      "rfw_prompts/web_research.jinja",
      "rfw_prompts/targeted_flag_research.jinja",
      "rfw_prompts/synthesis.jinja",
    ],
    writer: "RFW (no section_12.jinja)",
    models: ["sonar-pro", "sonar-deep-research", "claude-sonnet-4-6", "Gemini/OpenAI web fallbacks"],
    engine: "red_flag_workflow",
    langfuse: ["LLM_Call_Section_12"],
    notes: "Background from t≈0; collected before §1 so Conclusion sees red-flag digest. Groups A/E use sonar-deep-research + targeted dives.",
    calls: [
      { kind: "data_fetch_web", callee: "SerpAPI (rfw_serp.py)", purpose: "Preflight SERP" },
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro / deep-research", purpose: "Flag group web research" },
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 deterministic", purpose: "RFW synthesis" },
      { kind: "embedding_rag", callee: "Vertex/Gemini (+ optional AS)", purpose: "Evidence pack" },
    ],
    steps: [
      {
        id: "rfw.serp",
        name: "SerpAPI preflight",
        model: "rfw_serp.py",
        kind: "data_fetch_web",
      },
      {
        id: "rfw.web",
        name: "Step 1 — Parallel group web research",
        prompt: "web_research.jinja (+ targeted_flag_research.jinja)",
        model: "Perplexity (group A/E → deep-research)",
        kind: "reasoning_llm",
        detail: "Multi-LLM parallel per group; 600s wall timeout",
      },
      {
        id: "rfw.synth",
        name: "Synthesis",
        prompt: "synthesis.jinja",
        model: "claude-sonnet-4-6",
        kind: "reasoning_llm",
        detail: "Digest consumed by §1 Conclusion",
      },
    ],
  },
  {
    id: "1",
    name: "Conclusion",
    genOrder: 11,
    deps: ["2", "3", "4", "5", "6", "7", "8", "9", "10", "12"],
    templates: ["templates/sections/section_1.jinja", "src/retrieval/queries/query1.py"],
    writer: "call_claude_writing",
    models: ["claude-sonnet-4-6"],
    langfuse: ["LLM_Call_Section_1"],
    notes: "IC-first GLOBAL WRITING RULE. After §12, before §11. Consumes red-flag digest + prior sections.",
    calls: [
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6", purpose: "Write Conclusion" },
      { kind: "embedding_rag", callee: "Vertex / Gemini", purpose: "RAG §1" },
      { kind: "data_fetch_internal", callee: "Prior section outputs + RF digest", purpose: "Thesis inputs" },
    ],
    steps: [
      {
        id: "1.gather",
        name: "Gather prior sections + RF digest",
        kind: "data_fetch_internal",
      },
      {
        id: "1.write",
        name: "Conclusion write",
        prompt: "section_1.jinja",
        model: "call_claude_writing",
        kind: "reasoning_llm",
      },
    ],
  },
  {
    id: "11",
    name: "Research Challenge (ACS)",
    genOrder: 12,
    deps: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    templates: [
      "acs_prompts/step2_trigger_analysis.jinja",
      "acs_prompts/step3_contrarian_with_assessment.jinja",
      "acs_prompts/step4_cross_examination.jinja",
      "src/retrieval/alphasense_queries/query_11.py",
    ],
    writer: "ACS generate_section11_analyst_challenge",
    models: ["claude-sonnet-4-6"],
    engine: "analyst_challenge_workflow",
    langfuse: ["LLM_Call_Section_11"],
    notes: "No section_11.jinja. Runs last in production workflow order. AlphaSense RAG + full-report prompt cache.",
    calls: [
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 (+ prompt cache)", purpose: "ACS steps / contrarian challenge" },
      { kind: "embedding_rag", callee: "AlphaSense RAG + Vertex/Gemini", purpose: "§11 retrieval" },
      { kind: "data_fetch_internal", callee: "Full DD report + Company Review + excel_data", purpose: "Cross-examination inputs" },
    ],
    steps: [
      {
        id: "acs2",
        name: "Step 2 — Trigger & consensus analysis",
        prompt: "step2_trigger_analysis.jinja",
        model: "claude-sonnet-4-6",
        kind: "reasoning_llm",
        detail: "AlphaSense + Company Review sentiment context",
      },
      {
        id: "acs3",
        name: "Step 3 — Contrarian thesis + weight assessment",
        prompt: "step3_contrarian_with_assessment.jinja",
        model: "claude-sonnet-4-6",
        kind: "reasoning_llm",
        detail: "Opposing stance + quality-first assessment + RAG chunks",
      },
      {
        id: "acs4",
        name: "Step 4 — Management cross-examination",
        prompt: "step4_cross_examination.jinja",
        model: "claude-sonnet-4-6",
        kind: "reasoning_llm",
        detail: "5 management questions",
      },
    ],
  },
];

/** Optional post-DD / adjacent jobs (not in hot section loop) */
export const ddOptionalJobs = [
  {
    id: "h2h",
    name: "Head-to-Head (H2H)",
    detail: "Standalone regenerate-h2h. Landscape + tiered competitor chapters + synthesis. Langfuse: H2H_Competitor_Research.",
    templates: [
      "h2h/h2h_0_landscape.jinja",
      "h2h/h2h_p0_evidence_scan.jinja",
      "h2h/h2h_t2_dossier.jinja",
      "h2h/h2h_5_synthesis.jinja",
      "templates/research/h2h_competitor_research.jinja",
    ],
    models: ["Perplexity sonar-pro", "deepseek-v4-flash (stages/passes)"],
    calls: [
      { kind: "reasoning_llm", callee: "Perplexity sonar-pro", purpose: "Competitor research" },
      { kind: "reasoning_llm", callee: "DeepSeek deepseek-v4-flash", purpose: "Landscape / passes / verify" },
      { kind: "data_write_internal", callee: "EFS latest_h2h.json", purpose: "Persist H2H" },
    ],
    steps: [
      { id: "h2h0", name: "Stage 0 — Landscape + TRIAGE_JSON + POSITIONING_MAP", prompt: "h2h_0_landscape.jinja" },
      { id: "h2h05", name: "Stage 0.5 — Evidence scans (all comps concurrent)", prompt: "h2h_p0_evidence_scan.jinja" },
      { id: "h2ht1", name: "Tier1 P1–P4 — ledger → thesis → red_team → chapter (verify ≤2)", detail: "value_at_risk tiering" },
      { id: "h2ht2", name: "Tier2 dossier + verify", prompt: "h2h_t2_dossier.jinja" },
      { id: "h2h5", name: "Stage 5 — Competitive synthesis + full-report verify", prompt: "h2h_5_synthesis.jinja" },
    ],
  },
  {
    id: "risk",
    name: "Risk Auditor",
    detail: "Post-DD job on finished report JSON → risk_audit.json.",
    templates: ["src/engines/risk_auditor/ra_prompts/*"],
    models: ["deepseek-v4-flash (router/cluster/summary)", "claude-opus-4-7 (per-risk audit)"],
    calls: [
      { kind: "reasoning_llm", callee: "DeepSeek", purpose: "Link router + cluster + summary" },
      { kind: "reasoning_llm", callee: "claude-opus-4-7", purpose: "Per-risk audit (cached)" },
      { kind: "data_write_internal", callee: "EFS risk_audit.json", purpose: "Persist RA" },
    ],
    steps: [
      { id: "ra1", name: "Parse DD JSON" },
      { id: "ra2", name: "Deterministic extract evidence + risk signals" },
      { id: "ra25", name: "Link router (route_and_merge)", model: "Sonnet/DeepSeek path" },
      { id: "ra3", name: "Optional company-type overlay (OpCo / FI / Insurance)" },
      { id: "ra4", name: "Render whole DD to text for cached prompt" },
      { id: "ra5", name: "Cluster signals → major risks" },
      { id: "ra6", name: "Audit each risk (Opus); risk1 sync cache-warm, rest ∥ ≤5" },
      { id: "ra7", name: "Executive summary + renumber by materiality" },
      { id: "ra8", name: "Write risk_audit.json" },
    ],
  },
  {
    id: "brain",
    name: "Brain / skills mine",
    detail: "On-demand mine → .NET playbook upsert; can inject into §8 / report skills.",
    templates: ["src/brain/prompts/*"],
    models: ["claude-sonnet-4-6"],
    calls: [
      { kind: "reasoning_llm", callee: "claude-sonnet-4-6 deterministic", purpose: "Extract patterns" },
      { kind: "job_orchestrate", callee: ".NET /internal/brain/playbooks", purpose: "Upsert playbooks" },
    ],
    steps: [
      { id: "br1", name: "Mine report / artefacts", model: "claude-sonnet-4-6" },
      { id: "br2", name: "Upsert playbooks via .NET", kind: "job_orchestrate" },
    ],
  },
];

/** @param {string} id */
export function ddSectionById(id) {
  return ddSections.find((s) => s.id === id) ?? null;
}

/** Sections in generation order */
export function ddSectionsInGenOrder() {
  return ddGenOrder.map((id) => ddSectionById(id)).filter(Boolean);
}
