/** @type {import('./types.js').EcoEdge[]} */
export const edges = [
  // PI core
  {
    id: "e-fe-net",
    source: "pi-fe",
    target: "pi-net",
    type: "http_api",
    label: "JWT API",
    description: "SPA calls .NET BFF for auth, ticker requests, universe, costs, notes, brain.",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md", "projects/phoenician-intelligence-frontend/call-architecture.md"],
    endpoints: ["/api/Auth", "/api/TickerRequest", "/api/universe", "/api/costs"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-fe-py-proxy",
    source: "pi-fe",
    target: "pi-py",
    type: "proxy",
    label: "via /api/python",
    description: "Heavy AI/EFS/chatbot/prompt-lab traffic proxied FE → .NET PythonProxy → Python.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence-backend/call-architecture.md"],
    endpoints: ["/api/python/*"],
    files: ["Controllers/PythonProxyController.cs"],
    callKind: "proxy_forward",
  },
  {
    id: "e-net-py-jobs",
    source: "pi-net",
    target: "pi-py",
    type: "job",
    label: "Report jobs",
    description: "PythonReportService / Jobs / Brain submit DD generate, H2H, RA, mine/compile.",
    confidence: "confirmed",
    evidence: ["systems/data-flows.md", "systems/call-architecture.md"],
    endpoints: ["/api/reports/generate", "/jobs/submit", "/api/brain/mine"],
    callKind: "job_orchestrate",
  },
  {
    id: "e-py-net-cb",
    source: "pi-py",
    target: "pi-net",
    type: "callback",
    label: "report-completed",
    description: "Python httpx callback on report complete/fail → CallbacksController → SSE.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence/call-architecture.md"],
    endpoints: ["/api/internal/callbacks/report-completed"],
    callKind: "job_orchestrate",
  },
  {
    id: "e-net-efs",
    source: "pi-net",
    target: "efs-pi",
    type: "s3_efs",
    label: "Read/write shared DD disk",
    description:
      "Only PI .NET and PI Python mount this EFS. .NET reads/writes report markers and company artefacts used to serve DD to clients (including Portfolio via HTTP).",
    confidence: "confirmed",
    evidence: ["systems/overview.md", "systems/linkage-graph.md"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-py-efs",
    source: "pi-py",
    target: "efs-pi",
    type: "s3_efs",
    label: "Write DD reports",
    description:
      "Python writes progress.json, finished DD reports, CapIQ/PDF raw_data on the shared PI EFS (not mounted by Portfolio).",
    confidence: "confirmed",
    evidence: ["systems/data-flows.md", "systems/linkage-graph.md"],
    callKind: "data_write_internal",
  },
  {
    id: "e-net-rds",
    source: "pi-net",
    target: "rds-pi",
    type: "database",
    label: "EF Core",
    description: "All PI entity persistence (users, ticker requests, notes, costs).",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence-backend/controllers-inventory.md"],
    callKind: "data_write_internal",
  },
  {
    id: "e-fe-sse",
    source: "pi-net",
    target: "pi-fe",
    type: "realtime",
    label: "SSE status",
    description: "TickerRequest status-stream EventSource + SignalR company-notes hub.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence-frontend/call-architecture.md"],
    endpoints: ["/api/tickerrequest/status-stream", "/hubs/company-notes"],
    callKind: "realtime_push",
  },
  {
    id: "e-net-s3up",
    source: "pi-net",
    target: "s3-pi-uploads",
    type: "s3_efs",
    label: "Presign uploads",
    description: "Admin upload pipeline via S3Service.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence-backend/call-architecture.md"],
    callKind: "binary_media",
  },

  // Embeds from PI FE
  {
    id: "e-fe-pm",
    source: "pi-fe",
    target: "pm-fe",
    type: "iframe",
    label: "iframe embed",
    description: "PortfolioOptimizer page embeds Amplify SPA via VITE_PORTFOLIO_OPTIMIZER_URL.",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md"],
    files: ["pages/PortfolioOptimizer.tsx"],
    callKind: "other:embed",
  },
  {
    id: "e-fe-earnings",
    source: "pi-fe",
    target: "earnings",
    type: "iframe",
    label: "iframe embed",
    description: "EarningsTracker embed via VITE_EARNINGS_TRACKER_URL (CF).",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md"],
    callKind: "other:embed",
  },
  {
    id: "e-fe-screen",
    source: "pi-fe",
    target: "screen",
    type: "iframe",
    label: "iframe + postMessage",
    description: "CapiqAgent embeds sslip dashboard; PI_REQUEST_TICKER postMessage handoff.",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md", "projects/capiq-screen-agent/links.md"],
    endpoints: ["https://13-62-39-214.sslip.io/dashboard/"],
    callKind: "other:embed",
  },
  {
    id: "e-fe-linker",
    source: "pi-fe",
    target: "linker",
    type: "embed_nav",
    label: "nav + pi_auth",
    description: "Full navigation to /linker on same CF; cookie pi_auth validates on Lightsail.",
    confidence: "confirmed",
    evidence: ["systems/auth-boundaries.md", "systems/linkage-graph.md"],
    callKind: "auth_identity",
  },

  // Screen ↔ PI
  {
    id: "e-net-screen",
    source: "pi-net",
    target: "screen",
    type: "http_api",
    label: "/screen/universe",
    description: "ScreenAgentClient searches Screen universe (2500ms timeout, Postgres fallback).",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/call-architecture.md"],
    endpoints: ["GET /screen/universe"],
    files: ["Services/ScreenAgentClient.cs"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-screen-net-wh",
    source: "screen",
    target: "pi-net",
    type: "webhook",
    label: "Watch webhook",
    description: "screenBus notifies PI on Watch verdicts with X-Webhook-Key.",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/links.md"],
    files: ["backend/webhooks.js"],
    callKind: "data_write_internal",
  },
  {
    id: "e-screen-sqlite",
    source: "screen",
    target: "sqlite-screen",
    type: "database",
    label: "SQLite SoT",
    description: "memory.db + screening.db persistence on EC2.",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/architecture.md"],
    callKind: "data_write_internal",
  },

  // Portfolio
  {
    id: "e-pmfe-serve",
    source: "pm-fe",
    target: "pm-serve",
    type: "http_api",
    label: "PUBLIC_API_BASE",
    description: "Amplify SPA reads books / triggers jobs with optional X-Trigger-Token.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-pm-pi",
    source: "pm-serve",
    target: "pi-net",
    type: "http_api",
    label: "Fetch DD / risk / DCF",
    description:
      "Portfolio Manager does not mount PI EFS. pm-serve pi_client calls PI .NET /api/internal/universe* (X-Callback-Secret) and receives DD/risk/DCF bytes that PI already stores on its shared EFS. ensure_risk can kick incomplete risk jobs.",
    confidence: "confirmed",
    evidence: [
      "systems/linkage-graph.md",
      "systems/data-flows.md",
      "projects/phoenician-portfolio/call-architecture.md",
    ],
    endpoints: ["/api/internal/universe*"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-pm-s3",
    source: "pm-serve",
    target: "s3-strategy",
    type: "s3_efs",
    label: "Store books",
    description: "S3 STORE_READ/WRITE for custom/* and universe books.",
    confidence: "confirmed",
    evidence: ["systems/overview.md"],
    callKind: "data_write_internal",
  },
  {
    id: "e-pm-redis",
    source: "pm-serve",
    target: "redis-pm",
    type: "realtime",
    label: "LIVE tips",
    description: "Redis hot bus for LIVE quote tips.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md"],
    callKind: "realtime_push",
  },
  {
    id: "e-pm-aurora",
    source: "pm-serve",
    target: "aurora-pm",
    type: "database",
    label: "Dual-write mirror",
    description: "Optional Aurora mirror of store keys.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md"],
    callKind: "data_write_internal",
  },
  {
    id: "e-pm-ep",
    source: "pm-serve",
    target: "ep",
    type: "job",
    label: "ep-predict subprocess",
    description: "earnings_bridge runs EP advisory; never → book ER/weights.",
    confidence: "confirmed",
    evidence: ["systems/data-flows.md", "projects/phoenician-portfolio/kb-invariants.md"],
    callKind: "job_orchestrate",
  },
  {
    id: "e-s3-dynamo",
    source: "s3-strategy",
    target: "dynamo-book",
    type: "job",
    label: "Lambda book sync",
    description: "S3 custom/book.json → Lambda → Dynamo johns-portfolio for portal top5.",
    confidence: "confirmed",
    evidence: ["systems/data-flows.md", "systems/linkage-graph.md"],
    callKind: "job_orchestrate",
  },
  {
    id: "e-portal-dynamo",
    source: "portal-api",
    target: "dynamo-book",
    type: "database",
    label: "StrategyTop5",
    description: "Portal reads Dynamo weights + FMP re-rank for factsheet top5.",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/call-architecture.md"],
    callKind: "data_fetch_internal",
  },

  // Portal
  {
    id: "e-pweb-api",
    source: "portal-web",
    target: "portal-api",
    type: "http_api",
    label: "apiFetch JWT",
    description: "Admin/investor SPA → Portal API with Bearer + refresh cookie.",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/call-architecture.md"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-mobile-api",
    source: "portal-mobile",
    target: "portal-api",
    type: "http_api",
    label: "SecureStore JWT",
    description: "Both mobile forks hit portal-api (not PI).",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-mobile/call-architecture.md"],
    callKind: "data_fetch_internal",
  },
  {
    id: "e-portal-rds",
    source: "portal-api",
    target: "rds-portal",
    type: "database",
    label: "EF + Hangfire",
    description: "Domain persistence and Hangfire PostgreSQL store.",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/call-architecture.md"],
    callKind: "data_write_internal",
  },
  {
    id: "e-portal-s3docs",
    source: "portal-api",
    target: "s3-docs",
    type: "s3_efs",
    label: "Docs + quarantine",
    description: "Upload/scan/presign (~300s) for investor documents.",
    confidence: "confirmed",
    evidence: ["systems/data-flows.md"],
    callKind: "binary_media",
  },
  {
    id: "e-portal-factsheet",
    source: "portal-api",
    target: "factsheet",
    type: "conceptual",
    label: "admin twin",
    description: "Portal /strategy-factsheet is server-backed cousin of Factsheet-Automation (conceptual, not runtime import).",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md", "projects/Factsheet-Automation/links.md"],
    callKind: "other",
  },
  {
    id: "e-portal-mail",
    source: "portal-api",
    target: "mail-sender",
    type: "conceptual",
    label: "IrMail twin",
    description: "Shared Graph IR UX idea; separate deployments (portal IrMail vs loopback mail-sender).",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md"],
    callKind: "other:graph_mail",
  },
  {
    id: "e-mobile-fork",
    source: "portal-mobile",
    target: "portal-web",
    type: "fork",
    label: "fork ≠ sync",
    description: "Standalone mobile vs nested mobile-app diverge in screens/services.",
    confidence: "confirmed",
    evidence: ["systems/linkage-graph.md", "projects/investor-portal-mobile/screens-inventory.md"],
  },

  // Vendors — PI
  {
    id: "e-py-capiq",
    source: "pi-py",
    target: "capiq",
    type: "vendor",
    label: "Playwright dumps",
    description: "CapIQ Excel/PDF downloads into EFS (account rotation).",
    confidence: "confirmed",
    evidence: ["systems/cap-iq-and-screen.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-py-anthropic",
    source: "pi-py",
    target: "anthropic",
    type: "vendor",
    label: "DD sections",
    description: "Primary Claude generation for report sections, H2H, RA.",
    confidence: "confirmed",
    evidence: ["systems/ai-prompting-map.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-py-gemini",
    source: "pi-py",
    target: "gemini",
    type: "vendor",
    label: "RAG retrieve",
    description: "Vertex AI Search / Gemini File Search for section context.",
    confidence: "confirmed",
    evidence: ["systems/ai-prompting-map.md"],
    callKind: "embedding_rag",
  },
  {
    id: "e-py-deepseek",
    source: "pi-py",
    target: "deepseek",
    type: "vendor",
    label: "Cheap DD",
    description: "deepseek-v4-flash cheap generation path.",
    confidence: "confirmed",
    evidence: ["systems/ai-prompting-map.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-py-serpapi",
    source: "pi-py",
    target: "serpapi",
    type: "vendor",
    label: "SERP / scrape",
    description: "Red-flag SERP, IR email lookup, review scrapers.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence/call-architecture.md"],
    callKind: "data_fetch_web",
  },
  {
    id: "e-net-yahoo",
    source: "pi-net",
    target: "yahoo",
    type: "vendor",
    label: "MarketData",
    description: "Yahoo chart API for quotes/history.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence-backend/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-net-openai-tts",
    source: "pi-net",
    target: "openai",
    type: "vendor",
    label: "TTS proxy",
    description: "TextToSpeechController → OpenAI speech.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-intelligence-backend/call-architecture.md"],
    callKind: "binary_media",
  },

  // Vendors — Screen / Linker / Earnings / Portfolio
  {
    id: "e-screen-capiq",
    source: "screen",
    target: "capiq",
    type: "vendor",
    label: "Snowflake + pages",
    description: "CapIQ Snowflake reader + Chrome extension on CapIQ.com; sibling download jobs.",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-screen-claude",
    source: "screen",
    target: "anthropic",
    type: "vendor",
    label: "Chat + screen + Dreams",
    description: "Anthropic + Managed Memory/Dreams for Pass/Watch and PM chat.",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/ai-prompting.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-screen-yahoo",
    source: "screen",
    target: "yahoo",
    type: "vendor",
    label: "Live prices",
    description: "yahoo-finance2 quote feed / 15m refresh.",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/tiny-logic.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-linker-capiq",
    source: "linker",
    target: "capiq",
    type: "vendor",
    label: "Playwright resolve",
    description: "CapIQ login/search for companyId + Key Stats CLI downloads.",
    confidence: "confirmed",
    evidence: ["projects/Linker/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-linker-claude",
    source: "linker",
    target: "anthropic",
    type: "vendor",
    label: "CLI qualitative /40",
    description: "Claude qualitative scoring is CLI-only — Flask web has no LLM.",
    confidence: "confirmed",
    evidence: ["systems/ai-prompting-map.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-earnings-deepseek",
    source: "earnings",
    target: "deepseek",
    type: "vendor",
    label: "Summaries / extract",
    description: "DeepSeek via OpenAI SDK for finder/webcast/summary.",
    confidence: "confirmed",
    evidence: ["projects/Earnings_tracker/ai-prompting.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-earnings-serp",
    source: "earnings",
    target: "serpapi",
    type: "vendor",
    label: "IR search",
    description: "SerpAPI for smart_finder / webcast / summary_finder.",
    confidence: "confirmed",
    evidence: ["projects/Earnings_tracker/call-architecture.md"],
    callKind: "data_fetch_web",
  },
  {
    id: "e-pm-anthropic",
    source: "pm-serve",
    target: "anthropic",
    type: "vendor",
    label: "Stages 0–6 (Claude)",
    description: "Claude Sonnet/Opus/Fable for strategy pipeline, debate, lessons.",
    confidence: "confirmed",
    evidence: ["systems/ai-prompting-map.md", "projects/phoenician-portfolio/call-architecture.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-pm-deepseek",
    source: "pm-serve",
    target: "deepseek",
    type: "vendor",
    label: "Optional universe-run",
    description:
      "strategy/deepseek → api.deepseek.com for optional universe-run (deepseek-v4-flash) when configured via DEEPSEEK_*.",
    confidence: "confirmed",
    evidence: [
      "projects/phoenician-portfolio/call-architecture.md",
      "projects/phoenician-portfolio/ai-prompting.md",
      "systems/ai-prompting-map.md",
    ],
    callKind: "reasoning_llm",
  },
  {
    id: "e-pm-yahoo",
    source: "pm-serve",
    target: "yahoo",
    type: "vendor",
    label: "Prices / LIVE",
    description: "yfinance panels and LIVE last/prev close.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-pm-fmp",
    source: "pm-serve",
    target: "fmp",
    type: "vendor",
    label: "Rates / URTH",
    description: "FMP for Rf, VIX, ETF weights.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-ep-capiq",
    source: "ep",
    target: "capiq",
    type: "vendor",
    label: "capiq-downloader",
    description: "43 CapIQ artefacts via Playwright CLI on Hard refresh.",
    confidence: "confirmed",
    evidence: ["systems/cap-iq-and-screen.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-ep-anthropic",
    source: "ep",
    target: "anthropic",
    type: "vendor",
    label: "Judge + insider LLM",
    description: "EP llm_battery judge (Sonnet) and signals/insider_llm (Opus).",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md", "projects/phoenician-portfolio/earnings-predictor.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-ep-deepseek",
    source: "ep",
    target: "deepseek",
    type: "vendor",
    label: "Calendar date extract",
    description: "EP calendar/smart_finder uses DeepSeek chat (DEEPSEEK_MODEL) for IR date extraction.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-portfolio/call-architecture.md", "projects/phoenician-portfolio/earnings-predictor.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-screen-deepseek",
    source: "screen",
    target: "deepseek",
    type: "vendor",
    label: "Llama desk (:3004)",
    description: "Optional DeepSeek deepseek-v4-flash desk for Screen chat / triage when that provider is selected.",
    confidence: "confirmed",
    evidence: ["projects/capiq-screen-agent/ai-prompting.md", "projects/capiq-screen-agent/call-architecture.md"],
    callKind: "reasoning_llm",
  },

  // Portal vendors
  {
    id: "e-portal-openai",
    source: "portal-api",
    target: "openai",
    type: "vendor",
    label: "Doc AI extractors",
    description: "gpt-4o-mini/4o for rename, segment, contract notes (admin only).",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/ai-prompting.md"],
    callKind: "reasoning_llm",
  },
  {
    id: "e-portal-graph",
    source: "portal-api",
    target: "graph",
    type: "vendor",
    label: "IrMail sendMail",
    description: "Admin IR campaigns via Graph (client credentials).",
    confidence: "confirmed",
    evidence: ["systems/data-flows.md"],
    callKind: "other:graph_mail",
  },
  {
    id: "e-portal-resend",
    source: "portal-api",
    target: "resend",
    type: "vendor",
    label: "OTP / tx email",
    description: "Transactional email via Resend — not SES.",
    confidence: "confirmed",
    evidence: ["systems/auth-boundaries.md", "systems/COMPLETENESS.md"],
    callKind: "other:transactional_email",
  },
  {
    id: "e-portal-docuseal",
    source: "portal-api",
    target: "docuseal",
    type: "vendor",
    label: "E-sign",
    description: "DocuSeal live path; DocuSign class not DI-wired.",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/call-architecture.md"],
    callKind: "other:esign_vendor",
  },
  {
    id: "e-portal-fmp",
    source: "portal-api",
    target: "fmp",
    type: "vendor",
    label: "Top5 re-rank",
    description: "StrategyTop5Service uses FMP profile/EOD with Dynamo weights.",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-portal-yahoo",
    source: "portal-api",
    target: "yahoo",
    type: "vendor",
    label: "Quotes",
    description: "MarketDataService Yahoo quotes for portfolio companies.",
    confidence: "confirmed",
    evidence: ["projects/investor-portal-backend/call-architecture.md"],
    callKind: "data_fetch_market",
  },
  {
    id: "e-mail-graph",
    source: "mail-sender",
    target: "graph",
    type: "vendor",
    label: "sendMail",
    description: "Loopback FastAPI → Graph as ir@ mailbox.",
    confidence: "confirmed",
    evidence: ["projects/phoenician-mail-sender/call-architecture.md"],
    callKind: "other:graph_mail",
  },

  // Auth cookie PI → Linker (already have nav edge; add net issues cookie note as inferred from auth)
  {
    id: "e-net-linker-jwt",
    source: "pi-net",
    target: "linker",
    type: "jwt_cookie",
    label: "pi_auth secret",
    description: ".NET issues JWT; Linker validates same HS256 secret + CF Origin-Auth.",
    confidence: "confirmed",
    evidence: ["systems/auth-boundaries.md"],
    callKind: "auth_identity",
  },
];

/** @type {Map<string, import('./types.js').EcoEdge>} */
export const edgeById = new Map(edges.map((e) => [e.id, e]));
