/**
 * @typedef {import('./types.js').Journey & { plainSteps?: string[] }} RichJourney
 * @type {RichJourney[]}
 */
export const journeys = [
  {
    id: "j-dd",
    name: "How a DD report gets made",
    description: "From the analyst’s click to a finished research report on screen.",
    business: "diligence",
    plainSteps: [
      "Analyst opens Phoenician Intelligence and requests a company",
      "PI control records the job and who asked",
      "Job state is saved in the research database",
      "DD engine starts gathering data and writing sections",
      "Financials pulled from CapIQ",
      "Document search feeds context into the write",
      "AI models draft the diligence sections",
      "Report files land on the shared PI disk (EFS)",
      "DD engine tells PI control the job is finished",
      "The website updates live so the analyst can read it",
    ],
    steps: ["pi-fe", "pi-net", "rds-pi", "pi-py", "capiq", "gemini", "anthropic", "efs-pi", "pi-net", "pi-fe"],
    edgeIds: ["e-fe-net", "e-net-rds", "e-net-py-jobs", "e-py-capiq", "e-py-gemini", "e-py-anthropic", "e-py-efs", "e-py-net-cb", "e-fe-sse"],
  },
  {
    id: "j-screen-embed",
    name: "Open the Screener",
    description: "Jump from the research hub into CapIQ universe triage.",
    business: "screening",
    plainSteps: [
      "Analyst opens the Screener workspace inside Phoenician Intelligence",
      "Screener dashboard loads (embedded) with local SQLite memory",
      "AI chat / triage runs against the living framework",
      "Market context comes from CapIQ / Snowflake feeds",
      "Optionally PI control also searches Screener’s universe API",
    ],
    steps: ["pi-fe", "screen", "sqlite-screen", "anthropic", "capiq"],
    edgeIds: ["e-fe-screen", "e-screen-sqlite", "e-screen-claude", "e-screen-capiq", "e-net-screen"],
  },
  {
    id: "j-portfolio-run",
    name: "How portfolio research runs",
    description: "Build an investment book with AI stages, then pull diligence from Phoenician Intelligence.",
    business: "portfolio",
    plainSteps: [
      "Open the Portfolio Manager website",
      "Start a research / book stage run",
      "Claude (and optionally DeepSeek) runs the stage prompts",
      "Results are saved to the strategy storage bucket",
      "Portfolio asks Phoenician Intelligence for DD / risk / DCF over the network (not a shared disk)",
      "Live tips show up in the portfolio UI",
    ],
    steps: ["pm-fe", "pm-serve", "anthropic", "deepseek", "s3-strategy", "pi-net", "redis-pm"],
    edgeIds: ["e-pmfe-serve", "e-pm-anthropic", "e-pm-deepseek", "e-pm-s3", "e-pm-pi", "e-pm-redis"],
  },
  {
    id: "j-linker",
    name: "Link a CapIQ screening sheet",
    description: "Upload an Excel sheet → CapIQ hyperlinks get injected → download the patched file.",
    business: "screening",
    plainSteps: [
      "Analyst is already logged into PI",
      "Opens Linker and uploads a screening workbook",
      "Linker looks up companies on CapIQ",
      "Patched Excel with CapIQ hyperlinks is downloaded",
    ],
    steps: ["pi-fe", "linker", "capiq", "pi-net"],
    edgeIds: ["e-fe-linker", "e-linker-capiq", "e-net-linker-jwt"],
  },
  {
    id: "j-earnings",
    name: "Weekly earnings scrape + summary",
    description: "Scheduler finds earnings events, DeepSeek summarizes them, dashboard updates.",
    business: "earnings",
    plainSteps: [
      "Scheduler kicks off the earnings tracker",
      "DeepSeek extracts / ranks / summarizes events",
      "Web search helps find IR / webcast links",
      "Results appear in the earnings dashboard (also inside PI)",
    ],
    steps: ["earnings", "deepseek", "serpapi", "pi-fe"],
    edgeIds: ["e-earnings-deepseek", "e-earnings-serp", "e-fe-earnings"],
  },
  {
    id: "j-investor-doc",
    name: "Investor document upload",
    description: "Admin uploads a doc → it is scanned and stored → investor opens it later.",
    business: "investor",
    plainSteps: [
      "Admin uploads a document in the portal website",
      "Portal API stores it safely (scan, then clean folder)",
      "Metadata is recorded in the portal database",
      "Investor can later open it from the mobile app",
    ],
    steps: ["portal-web", "portal-api", "s3-docs", "rds-portal", "portal-mobile"],
    edgeIds: ["e-pweb-api", "e-portal-s3docs", "e-portal-rds", "e-mobile-api"],
  },
  {
    id: "j-ir-mail",
    name: "Send IR campaign email",
    description: "Admin writes a campaign in the portal → Microsoft Graph delivers it.",
    business: "ir_comms",
    plainSteps: [
      "Admin composes an IR campaign in the portal",
      "Portal API sends via Microsoft Graph as IR",
      "Graph delivers the mail",
    ],
    steps: ["portal-web", "portal-api", "graph"],
    edgeIds: ["e-pweb-api", "e-portal-graph"],
  },
  {
    id: "j-strategy-book",
    name: "Strategy book → portal factsheet",
    description: "Portfolio saves a book → portal picks it up → admin factsheet shows top holdings.",
    business: "marketing",
    plainSteps: [
      "Portfolio writes the strategy book to storage",
      "A job mirrors weights into the portal’s book table",
      "Portal reads the strategy book",
      "Live prices re-rank top holdings",
      "Admin factsheet UI shows the result",
    ],
    steps: ["pm-serve", "s3-strategy", "dynamo-book", "portal-api", "fmp", "portal-web"],
    edgeIds: ["e-pm-s3", "e-s3-dynamo", "e-portal-dynamo", "e-portal-fmp", "e-pweb-api"],
  },
  {
    id: "j-watch-webhook",
    name: "Screener Watch → PI",
    description: "Screener finishes Pass/Watch triage and notifies Phoenician Intelligence.",
    business: "screening",
    plainSteps: [
      "Screener finishes a Pass/Watch triage",
      "AI judgment is part of that triage",
      "A notification reaches Phoenician Intelligence",
      "Analyst sees the update in the PI website",
    ],
    steps: ["screen", "anthropic", "pi-net", "pi-fe"],
    edgeIds: ["e-screen-claude", "e-screen-net-wh", "e-fe-net"],
  },
];
