/** @type {import('./types.js').Journey[]} */
export const journeys = [
  {
    id: "j-dd",
    name: "Generate a DD report",
    description: "Analyst requests a ticker → .NET persists → Python RAG+LLM → EFS → callback → SSE to SPA.",
    business: "diligence",
    steps: ["pi-fe", "pi-net", "rds-pi", "pi-py", "capiq", "gemini", "anthropic", "efs-pi", "pi-net", "pi-fe"],
    edgeIds: ["e-fe-net", "e-net-rds", "e-net-py-jobs", "e-py-capiq", "e-py-gemini", "e-py-anthropic", "e-py-efs", "e-py-net-cb", "e-fe-sse"],
  },
  {
    id: "j-screen-embed",
    name: "Open CapIQ Screen from PI",
    description: "PI hub iframe → Screen dashboard; .NET may also query /screen/universe.",
    business: "screening",
    steps: ["pi-fe", "screen", "sqlite-screen", "anthropic", "capiq"],
    edgeIds: ["e-fe-screen", "e-screen-sqlite", "e-screen-claude", "e-screen-capiq", "e-net-screen"],
  },
  {
    id: "j-portfolio-run",
    name: "Run portfolio research",
    description: "PM FE triggers pm-serve → Claude stages → S3 books; optional PI universe bytes.",
    business: "portfolio",
    steps: ["pm-fe", "pm-serve", "anthropic", "s3-strategy", "pi-net", "redis-pm"],
    edgeIds: ["e-pmfe-serve", "e-pm-anthropic", "e-pm-s3", "e-pm-pi", "e-pm-redis"],
  },
  {
    id: "j-linker",
    name: "Link a CapIQ screening sheet",
    description: "PI login cookie → Linker Flask → CapIQ resolve → BIFF patch download.",
    business: "screening",
    steps: ["pi-fe", "linker", "capiq", "pi-net"],
    edgeIds: ["e-fe-linker", "e-linker-capiq", "e-net-linker-jwt"],
  },
  {
    id: "j-earnings",
    name: "Weekly earnings scrape + summary",
    description: "EventBridge → Lambda/API → DeepSeek/SerpAPI → Postgres → CF SPA (also PI embed).",
    business: "earnings",
    steps: ["earnings", "deepseek", "serpapi", "pi-fe"],
    edgeIds: ["e-earnings-deepseek", "e-earnings-serp", "e-fe-earnings"],
  },
  {
    id: "j-investor-doc",
    name: "Investor document upload",
    description: "Admin upload → quarantine S3 → scan → clean → RDS meta → investor presign.",
    business: "investor",
    steps: ["portal-web", "portal-api", "s3-docs", "rds-portal", "portal-mobile"],
    edgeIds: ["e-pweb-api", "e-portal-s3docs", "e-portal-rds", "e-mobile-api"],
  },
  {
    id: "j-ir-mail",
    name: "Send IR campaign email",
    description: "Admin IrMail → Portal Graph sendMail (or local mail-sender twin).",
    business: "ir_comms",
    steps: ["portal-web", "portal-api", "graph"],
    edgeIds: ["e-pweb-api", "e-portal-graph"],
  },
  {
    id: "j-strategy-book",
    name: "Strategy book → portal factsheet",
    description: "S3 custom/book.json → Lambda → Dynamo → Portal top5 (+ FMP).",
    business: "marketing",
    steps: ["pm-serve", "s3-strategy", "dynamo-book", "portal-api", "fmp", "portal-web"],
    edgeIds: ["e-pm-s3", "e-s3-dynamo", "e-portal-dynamo", "e-portal-fmp", "e-pweb-api"],
  },
  {
    id: "j-watch-webhook",
    name: "Screen Watch → PI",
    description: "Screen Pass/Watch triage fires webhook into PI .NET.",
    business: "screening",
    steps: ["screen", "anthropic", "pi-net", "pi-fe"],
    edgeIds: ["e-screen-claude", "e-screen-net-wh", "e-fe-net"],
  },
];
