/** @type {import('./types.js').EcoNode[]} */
export const nodes = [
  // ── Intelligence cluster (left-center) ───────────────────────────
  {
    id: "pi-fe",
    kind: "application",
    domain: "intelligence",
    name: "Phoenician Intelligence website",
    shortName: "PI website",
    purpose: "Multi-workspace research shell: diligence, embeds, costs, brain, notes, PDF/TTS.",
    why: "Single pane for analysts to run DD and open CapIQ/Portfolio/Earnings without leaving PI.",
    stack: ["React 18", "Vite", "TanStack Query", "SignalR client"],
    techLayer: "frontend",
    business: ["diligence", "screening"],
    tags: ["spa", "embed-host", "jwt"],
    urls: ["https://pi.phoeniciancapital.com"],
    repo: "phoenician-intelligence-frontend",
    runtime: "S3 + CloudFront E2CF5P57BJV2U3",
    entryPoints: ["src/App.tsx", "src/services/apiClient.ts"],
    modules: ["Dashboard", "CapiqAgent", "PortfolioOptimizer", "EarningsTracker", "BrainPlaybooks", "CompanyNotes"],
    apis: ["VITE_API_URL → .NET", "/api/python proxy", "hubs/company-notes"],
    callKinds: ["data_fetch_internal", "realtime_push", "job_orchestrate", "other:embed"],
    kb: "projects/phoenician-intelligence-frontend",
    x: 580,
    y: 400,
    r: 36,
  },
  {
    id: "pi-net",
    kind: "service",
    domain: "intelligence",
    name: "PI control tower (.NET)",
    shortName: "PI control",
    purpose: "Auth/OTP, ticker requests, Python orchestration, universe search, SignalR notes, billing, TTS.",
    why: "Control tower between the research website and the DD engine; owns RDS lifecycle and callbacks.",
    stack: ["net8.0", "EF Core", "JWT", "SignalR", "MailKit"],
    techLayer: "backend",
    business: ["diligence", "screening"],
    tags: ["bff", "eb", "jwt", "pathbase-/api"],
    urls: ["https://api.phoeniciancapital.com"],
    repo: "phoenician-intelligence-backend",
    runtime: "Elastic Beanstalk phoenician-api-prod",
    entryPoints: ["Program.cs", "Controllers/*"],
    modules: ["Auth", "TickerRequest", "PythonProxy", "CompanyNotesHub", "VendorBilling", "ScreenAgentClient"],
    apis: ["/api/Auth", "/api/TickerRequest", "/api/python/*", "/api/universe", "/hubs/company-notes"],
    databases: ["rds-pi", "efs-pi", "s3-pi-uploads"],
    callKinds: ["proxy_forward", "job_orchestrate", "billing_vendor", "realtime_push"],
    kb: "projects/phoenician-intelligence-backend",
    x: 760,
    y: 540,
    r: 38,
  },
  {
    id: "pi-py",
    kind: "service",
    domain: "intelligence",
    name: "Phoenician DD engine (Python)",
    shortName: "DD engine",
    purpose: "Async DD factory: CapIQ/PDF → RAG → 12-section report → UE-DCF, H2H, risk, chatbot, brain.",
    why: "Heavy AI + file work isolated from .NET; writes finished reports to the shared PI disk (EFS).",
    stack: ["FastAPI", "Claude/OpenAI/DeepSeek/Gemini", "Playwright", "LibreOffice", "Vertex RAG"],
    techLayer: "backend",
    business: ["diligence"],
    tags: ["ecs", "llm", "rag", "capiq"],
    urls: ["internal :8000"],
    repo: "phoenician-intelligence",
    runtime: "ECS phoenician-intelligence-service · 2 uvicorn workers",
    entryPoints: ["api/main.py", "src/engines/reportGenerator.py"],
    modules: ["workflow", "h2h", "risk_auditor", "brain", "prefetch", "RAG"],
    apis: ["/api/reports/generate", "/api/reports/status", "/chatbot/*", "/api/brain/*"],
    databases: ["efs-pi"],
    callKinds: ["reasoning_llm", "embedding_rag", "data_fetch_market", "data_fetch_web"],
    kb: "projects/phoenician-intelligence",
    x: 940,
    y: 400,
    r: 40,
  },
  {
    id: "earnings",
    kind: "service",
    domain: "intelligence",
    name: "Earnings Tracker",
    shortName: "Earnings Tracker",
    purpose: "IR calendar scrape + DeepSeek summaries + React dashboard.",
    why: "Research-hub satellite — embedded from the PI website (≠ portfolio earnings_predictor).",
    stack: ["Lambda", "FastAPI", "Postgres", "DeepSeek", "Playwright", "React"],
    techLayer: "backend",
    business: ["earnings"],
    tags: ["lambda", "embed-target"],
    urls: ["https://earnings.phoeniciancapital.com"],
    repo: "Earnings_tracker",
    runtime: "Lambda + ECS API + CF",
    callKinds: ["reasoning_llm", "data_fetch_web", "job_orchestrate"],
    kb: "projects/Earnings_tracker",
    x: 520,
    y: 220,
    r: 28,
  },

  // ── Portfolio ────────────────────────────────────────────────────
  {
    id: "pm-fe",
    kind: "application",
    domain: "portfolio",
    name: "Portfolio Manager website",
    shortName: "PM website",
    purpose: "Svelte SPA for two books, trades, lessons, debate, universe views.",
    why: "Operator UI for the Portfolio API; embedded in the PI hub.",
    stack: ["SvelteKit 5", "Amplify"],
    techLayer: "frontend",
    business: ["portfolio"],
    tags: ["spa", "amplify", "embed-target"],
    urls: ["https://main.d13pt3zp42x49n.amplifyapp.com"],
    repo: "phoenician-portfolio/portfolio_manager_frontend",
    runtime: "Amplify d13pt3zp42x49n",
    entryPoints: ["src/routes/+page", "src/lib/api.js"],
    callKinds: ["data_fetch_internal", "job_orchestrate"],
    kb: "projects/phoenician-portfolio",
    x: 1180,
    y: 220,
    r: 32,
  },
  {
    id: "pm-serve",
    kind: "service",
    domain: "portfolio",
    name: "Portfolio Manager API (pm-serve)",
    shortName: "Portfolio API",
    purpose: "Builds investment books, runs research stages, serves live tips, and talks to Phoenician Intelligence.",
    why: "Owns AI book sizing + advisory jobs; pulls DD/risk/DCF from PI over HTTP (not via EFS mount).",
    stack: ["Python", "Express-style serve", "Claude/DeepSeek", "yfinance"],
    techLayer: "backend",
    business: ["portfolio"],
    tags: ["ecs", "llm", "two-books"],
    urls: ["pm-*.ecs.eu-north-1.on.aws"],
    repo: "phoenician-portfolio/portfolio_manager",
    runtime: "ECS pm-serve-1b08",
    entryPoints: ["server/handler", "strategy/pipeline"],
    modules: ["strategy", "earnings_bridge", "pi_client", "redis_hot", "debate"],
    databases: ["s3-strategy", "redis-pm", "aurora-pm"],
    callKinds: ["reasoning_llm", "data_fetch_market", "job_orchestrate"],
    kb: "projects/phoenician-portfolio",
    x: 1380,
    y: 340,
    r: 36,
  },
  {
    id: "ep",
    kind: "satellite",
    domain: "portfolio",
    name: "Earnings predictor (portfolio)",
    shortName: "EP (portfolio)",
    purpose: "Next-print advisory research (never feeds ER/weights).",
    why: "Hard/soft earnings signals for PM; separate from Earnings Tracker calendar product.",
    stack: ["Python", "Claude/DeepSeek", "CapIQ downloader"],
    techLayer: "worker",
    business: ["portfolio", "earnings"],
    tags: ["advisory", "subprocess"],
    repo: "phoenician-portfolio/earnings_predictor",
    kb: "projects/phoenician-portfolio/earnings-predictor.md",
    x: 1520,
    y: 220,
    r: 22,
  },

  // ── Portal ───────────────────────────────────────────────────────
  {
    id: "portal-web",
    kind: "application",
    domain: "portal",
    name: "Investor Portal Web",
    shortName: "Portal Web",
    purpose: "Admin + investor React: docs, KYC, forms, IrMail, strategy factsheet.",
    why: "Staff ops + investor self-serve in one SPA shell.",
    stack: ["React", "Vite"],
    techLayer: "frontend",
    business: ["investor", "ir_comms"],
    tags: ["spa", "admin", "jwt"],
    urls: ["https://invest.phoeniciancapital.com"],
    repo: "investor-portal-backend/admin-portal",
    runtime: "CloudFront + S3",
    entryPoints: ["App.tsx", "investor/InvestorPortal.tsx"],
    callKinds: ["data_fetch_internal", "other:graph_mail", "other:esign_vendor"],
    kb: "projects/investor-portal-backend",
    x: 1180,
    y: 720,
    r: 32,
  },
  {
    id: "portal-api",
    kind: "service",
    domain: "portal",
    name: "Portal API",
    shortName: "Portal API",
    purpose: "net8 Clean Architecture: auth, docs, KYC, DocuSeal, IrMail Graph, OpenAI rename, Hangfire.",
    why: "Investor data plane — separate JWT island from PI.",
    stack: ["net8.0", "MediatR", "Hangfire", "DocuSeal", "Resend", "Graph"],
    techLayer: "backend",
    business: ["investor", "ir_comms", "marketing"],
    tags: ["ecs", "jwt", "not-cognito"],
    urls: ["https://portal-api.phoeniciancapital.com"],
    repo: "investor-portal-backend",
    runtime: "WAF → ALB → ECS Fargate",
    entryPoints: ["Program.cs", "Features/*"],
    modules: ["Auth", "Documents", "IrMail", "KYC", "StrategyBook", "OpenAi*"],
    databases: ["rds-portal", "s3-docs", "dynamo-book"],
    callKinds: ["reasoning_llm", "other:transactional_email", "other:graph_mail", "job_orchestrate"],
    kb: "projects/investor-portal-backend",
    x: 1380,
    y: 820,
    r: 36,
  },
  {
    id: "portal-mobile",
    kind: "application",
    domain: "portal",
    name: "Investor Portal Mobile",
    shortName: "Mobile",
    purpose: "Expo investor apps (standalone 1.2.0 + nested fork) against portal API.",
    why: "On-the-go docs/KYC/push — forks diverge.",
    stack: ["Expo", "React Native"],
    techLayer: "client",
    business: ["investor"],
    tags: ["expo", "fork"],
    repo: "investor-portal-mobile",
    runtime: "EAS / App Store",
    callKinds: ["data_fetch_internal", "realtime_push", "auth_identity"],
    kb: "projects/investor-portal-mobile",
    x: 1180,
    y: 900,
    r: 26,
  },

  // ── Screener (own product box — peer to Research hub / Portfolio / Investors) ──
  {
    id: "screen",
    kind: "service",
    domain: "screener",
    name: "Screener (CapIQ Screen Agent)",
    shortName: "Screener",
    purpose: "Chrome ext + Express: chat with PM framework, Pass/Watch screen ~16k, Dreams memory.",
    why: "Core product with its own map box — embeds in the PI shell but owns its EC2 stack.",
    stack: ["Node/Express", "SQLite", "Anthropic Managed Memory", "Yahoo", "Snowflake"],
    techLayer: "backend",
    business: ["screening"],
    tags: ["ec2", "llm", "embed-target", "capiq"],
    urls: ["https://13-62-39-214.sslip.io/dashboard/", "http://13.62.39.214:3001"],
    repo: "capiq-screen-agent",
    runtime: "EC2 i-0ef36803457fc6db4 · PM2 :3001–3004",
    entryPoints: ["backend/server.js", "extension/content.js"],
    modules: ["screening-worker", "memory", "managed-agents", "auditor-gate"],
    databases: ["sqlite-screen"],
    callKinds: ["reasoning_llm", "data_fetch_market", "realtime_push"],
    kb: "projects/capiq-screen-agent",
    x: 180,
    y: 380,
    r: 40,
  },
  {
    id: "linker",
    kind: "service",
    domain: "screener",
    name: "Linker",
    shortName: "Linker",
    purpose: "Flask CapIQ hyperlink injector + CLI capital-allocation ranking (/100).",
    why: "Make screening sheets clickable; lives in the Screener box (CLI qualitative≠web).",
    stack: ["Flask", "Playwright", "Claude CLI", "BIFF"],
    techLayer: "backend",
    business: ["screening"],
    tags: ["lightsail", "capiq", "pi_auth"],
    urls: ["https://pi.phoeniciancapital.com/linker"],
    repo: "Linker",
    runtime: "Lightsail 63.184.47.249 eu-central-1",
    entryPoints: ["capiq_linker/app.py", "analyze_capital_allocation.py"],
    callKinds: ["data_fetch_market", "binary_media", "auth_identity"],
    kb: "projects/Linker",
    x: 100,
    y: 520,
    r: 28,
  },

  // ── Side tools (Factsheet + Mail only — compact, not Screener) ──
  {
    id: "factsheet",
    kind: "application",
    domain: "ops",
    name: "Factsheet Automation",
    shortName: "Factsheet",
    purpose: "Client-only marketing PDF/Excel for Phoenician Offshore Fund Ltd.",
    why: "Collateral — not live book truth (admin twin on portal).",
    stack: ["React 19", "Vite", "jsPDF"],
    techLayer: "frontend",
    business: ["marketing"],
    tags: ["static", "no-llm"],
    repo: "Factsheet-Automation",
    callKinds: ["binary_media"],
    kb: "projects/Factsheet-Automation",
    x: 200,
    y: 900,
    r: 22,
  },
  {
    id: "mail-sender",
    kind: "application",
    domain: "ops",
    name: "phoenician-mail-sender",
    shortName: "Mail Sender",
    purpose: "Loopback IR bulk mail via Microsoft Graph.",
    why: "Workstation twin of portal IrMail (different stack).",
    stack: ["FastAPI :8010", "Vite", "Graph"],
    techLayer: "backend",
    business: ["ir_comms"],
    tags: ["loopback", "graph"],
    repo: "phoenician-mail-sender",
    runtime: "127.0.0.1 only",
    callKinds: ["other:graph_mail", "realtime_push"],
    kb: "projects/phoenician-mail-sender",
    x: 320,
    y: 980,
    r: 22,
  },

  // ── Infra ────────────────────────────────────────────────────────
  {
    id: "rds-pi",
    kind: "database",
    domain: "infra",
    name: "RDS investor_platform_db",
    shortName: "RDS PI",
    purpose: "PI .NET entities: users, ticker requests, notes, costs, playbooks.",
    stack: ["Postgres"],
    techLayer: "data",
    business: ["diligence"],
    tags: ["rds", "postgres"],
    x: 740,
    y: 700,
    r: 18,
  },
  {
    id: "efs-pi",
    kind: "infrastructure",
    domain: "infra",
    name: "PI shared disk (EFS)",
    shortName: "PI EFS",
    purpose:
      "Shared file disk for DD artefacts, CapIQ dumps, progress markers — mounted only by PI .NET and PI Python. Portfolio gets those bytes via the PI API, not by mounting this disk.",
    stack: ["EFS fs-069a92a202a9402c5"],
    techLayer: "infra",
    business: ["diligence"],
    tags: ["efs"],
    // Keep under the PI cluster so Portfolio API → PI control does not visually skim this node
    x: 820,
    y: 660,
    r: 18,
  },
  {
    id: "s3-pi-uploads",
    kind: "infrastructure",
    domain: "infra",
    name: "S3 PI uploads",
    shortName: "S3 uploads",
    purpose: "Presigned admin uploads for PI.",
    stack: ["S3"],
    techLayer: "infra",
    business: ["diligence"],
    tags: ["s3"],
    x: 620,
    y: 660,
    r: 16,
  },
  {
    id: "s3-strategy",
    kind: "infrastructure",
    domain: "infra",
    name: "S3 phoenician-capital-strategy",
    shortName: "S3 strategy",
    purpose: "Portfolio books custom/* + books/universe/**.",
    stack: ["S3"],
    techLayer: "infra",
    business: ["portfolio"],
    tags: ["s3", "books"],
    x: 1480,
    y: 460,
    r: 18,
  },
  {
    id: "redis-pm",
    kind: "infrastructure",
    domain: "infra",
    name: "Redis LIVE tips",
    shortName: "Redis",
    purpose: "Hot quote tips bus for portfolio LIVE.",
    stack: ["Redis"],
    techLayer: "infra",
    business: ["portfolio"],
    tags: ["redis"],
    x: 1280,
    y: 460,
    r: 16,
  },
  {
    id: "aurora-pm",
    kind: "database",
    domain: "infra",
    name: "Aurora store mirror",
    shortName: "Aurora",
    purpose: "Optional dual-write mirror of strategy store keys.",
    stack: ["Aurora/Postgres"],
    techLayer: "data",
    business: ["portfolio"],
    tags: ["aurora"],
    x: 1580,
    y: 380,
    r: 16,
  },
  {
    id: "rds-portal",
    kind: "database",
    domain: "infra",
    name: "Portal RDS + Hangfire",
    shortName: "RDS Portal",
    purpose: "Investor domain + Hangfire job store.",
    stack: ["Postgres"],
    techLayer: "data",
    business: ["investor"],
    tags: ["rds"],
    x: 1480,
    y: 920,
    r: 18,
  },
  {
    id: "s3-docs",
    kind: "infrastructure",
    domain: "infra",
    name: "S3 documents (+ quarantine)",
    shortName: "S3 docs",
    purpose: "Investor docs with scan → clean promote.",
    stack: ["S3"],
    techLayer: "infra",
    business: ["investor"],
    tags: ["s3", "presign"],
    x: 1280,
    y: 980,
    r: 16,
  },
  {
    id: "dynamo-book",
    kind: "database",
    domain: "infra",
    name: "Dynamo strategy-book",
    shortName: "Dynamo",
    purpose: "johns-portfolio weights for portal top5 / factsheet.",
    stack: ["DynamoDB"],
    techLayer: "data",
    business: ["investor", "marketing"],
    tags: ["dynamo", "lambda-sync"],
    x: 1580,
    y: 860,
    r: 16,
  },
  {
    id: "sqlite-screen",
    kind: "database",
    domain: "screener",
    name: "Screener SQLite DBs",
    shortName: "SQLite",
    purpose: "memory.db + screening.db + financials/live-prices on EC2.",
    stack: ["better-sqlite3"],
    techLayer: "data",
    business: ["screening"],
    tags: ["sqlite"],
    x: 80,
    y: 620,
    r: 16,
  },

  // ── Vendors ──────────────────────────────────────────────────────
  {
    id: "capiq",
    kind: "external",
    domain: "vendor",
    name: "Capital IQ",
    shortName: "CapIQ",
    purpose: "Financials, screening, Snowflake MI_XPRESSCLOUD, Playwright dumps.",
    stack: ["CapIQ web", "Snowflake"],
    techLayer: "vendor",
    business: ["diligence", "screening", "portfolio"],
    tags: ["vendor", "market-data"],
    x: 80,
    y: 320,
    r: 26,
  },
  {
    id: "anthropic",
    kind: "external",
    domain: "vendor",
    name: "Anthropic Claude",
    shortName: "Claude",
    purpose: "Primary reasoning LLM for DD, portfolio, screen, linker CLI.",
    stack: ["Anthropic API", "Managed Agents"],
    techLayer: "vendor",
    business: ["diligence", "portfolio", "screening"],
    tags: ["llm", "vendor"],
    x: 1100,
    y: 100,
    r: 24,
  },
  {
    id: "openai",
    kind: "external",
    domain: "vendor",
    name: "OpenAI",
    shortName: "OpenAI",
    purpose: "Portal extractors, PI TTS, some DCF/judge paths.",
    stack: ["OpenAI API"],
    techLayer: "vendor",
    business: ["investor", "diligence"],
    tags: ["llm", "tts", "vendor"],
    x: 1680,
    y: 780,
    r: 20,
  },
  {
    id: "deepseek",
    kind: "external",
    domain: "vendor",
    name: "DeepSeek",
    shortName: "DeepSeek",
    purpose: "Cheap DD, earnings summaries, optional Portfolio universe-run, Screen Llama desk, EP calendar extract.",
    stack: ["DeepSeek API"],
    techLayer: "vendor",
    business: ["diligence", "earnings", "portfolio", "screening"],
    tags: ["llm", "vendor"],
    // Sit above Portfolio so Portfolio API → DeepSeek does not cross PI EFS
    x: 1320,
    y: 120,
    r: 20,
  },
  {
    id: "gemini",
    kind: "external",
    domain: "vendor",
    name: "Vertex / Gemini RAG",
    shortName: "Vertex",
    purpose: "PI section RAG via Discovery Engine / File Search (GCP WIF).",
    stack: ["GCP Vertex", "Gemini"],
    techLayer: "vendor",
    business: ["diligence"],
    tags: ["rag", "vendor"],
    x: 980,
    y: 280,
    r: 20,
  },
  {
    id: "yahoo",
    kind: "external",
    domain: "vendor",
    name: "Yahoo Finance",
    shortName: "Yahoo",
    purpose: "Quotes/FX for PI, portfolio, screen, portal MarketData.",
    stack: ["yfinance", "chart API"],
    techLayer: "vendor",
    business: ["diligence", "portfolio", "investor"],
    tags: ["market-data", "vendor"],
    x: 1680,
    y: 280,
    r: 18,
  },
  {
    id: "fmp",
    kind: "external",
    domain: "vendor",
    name: "Financial Modeling Prep",
    shortName: "FMP",
    purpose: "Profiles/EOD for portfolio rates, PI FE, portal top5, factsheet dev.",
    stack: ["FMP API"],
    techLayer: "vendor",
    business: ["portfolio", "marketing"],
    tags: ["market-data", "vendor"],
    x: 1680,
    y: 420,
    r: 18,
  },
  {
    id: "graph",
    kind: "external",
    domain: "vendor",
    name: "Microsoft Graph",
    shortName: "Graph",
    purpose: "IR sendMail for portal IrMail + local mail-sender.",
    stack: ["Azure AD", "Graph sendMail"],
    techLayer: "vendor",
    business: ["ir_comms"],
    tags: ["email", "vendor"],
    x: 1680,
    y: 600,
    r: 20,
  },
  {
    id: "resend",
    kind: "external",
    domain: "vendor",
    name: "Resend",
    shortName: "Resend",
    purpose: "Portal transactional email (OTP, KYC warnings) — not SES.",
    stack: ["Resend API"],
    techLayer: "vendor",
    business: ["investor"],
    tags: ["email", "vendor"],
    x: 1580,
    y: 1040,
    r: 16,
  },
  {
    id: "docuseal",
    kind: "external",
    domain: "vendor",
    name: "DocuSeal",
    shortName: "DocuSeal",
    purpose: "Live e-sign for investor forms (DocuSign class unwired).",
    stack: ["DocuSeal API"],
    techLayer: "vendor",
    business: ["investor"],
    tags: ["esign", "vendor"],
    x: 1280,
    y: 1080,
    r: 16,
  },
  {
    id: "serpapi",
    kind: "external",
    domain: "vendor",
    name: "SerpAPI / web scrape",
    shortName: "SerpAPI",
    purpose: "Web search for PI red-flags, earnings finders, EP calendar.",
    stack: ["SerpAPI", "ScraperAPI"],
    techLayer: "vendor",
    business: ["diligence", "earnings"],
    tags: ["web", "vendor"],
    x: 320,
    y: 80,
    r: 16,
  },
];

/** @type {Map<string, import('./types.js').EcoNode>} */
export const nodeById = new Map(nodes.map((n) => [n.id, n]));
